<?php

/**
 * ProcessWire, Page Edit Soft Lock  Module 1.0.0
 *
 * This module provides function to update edit lock status
 * It will get called through from PageEditSoftLock's js script when editing a page
 *
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2011 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 *
 * @author Philipp 'Soma' Urlich, philipp at urlich dot com
 *
 * @date 27/10/2011
 * 
 *
 */

class PageEditSoftLock extends WireData implements Module, ConfigurableModule {
	
	static protected $defaults = array(
		'pingInterval' => 20000,
		'removeLockTimeout' => 60
		);
	
	public static function getModuleInfo() {
		return array(
			'title' => 'Page Edit Soft Lock',
			'summary' => 'Throws alert message when page is being edited by another user.',
			'version' => 100,
			'href' => 'http://processwire.com/talk/index.php/topic,637.0.html',
			'permanent' => false,
			'singular' => true, 
			'autoload' => true
		);
	}


	public function init() {
		$this->addHookAfter('ProcessPageEdit::execute', $this, 'checkpagestatus');
	}

	
	public function checkpagestatus(HookEvent $event){
		
		$config = self::$defaults;
		foreach($config as $key => $unused) {
			$config[$key] = $this->get($key) ? $this->get($key) : $config[$key] ;
		}
		
		$expiredTime = time() - $config['removeLockTimeout']; // default 60 seconds ago
		
		// delete all entries older than set removeLockTimeout
		$this->db->query("DELETE FROM users_editing_page WHERE ts <= $expiredTime"); 
		
		// get current page being edited
		$process = $event->object;
		$page = $process->getPage(); 

		$pingurl = $this->config->urls->admin . "page/edit/checkpagelock/updatestatus/";
		$interval = $config["pingInterval"];
		$script = <<< _END

<script type="text/javascript">

$(function(){
	var t = window.setInterval(ping,$interval);
	function ping(){
	
		$.ajax({
			url: '$pingurl',
			type: 'get',
			data: 'user_id={$this->user->id}&page_id={$page->id}',
			success: function(data){
				//alert('udpated');
			}
		});
	}
	
	
});

</script>
_END;
		// check for entries in table with this page id
		$result = $this->db->query("SELECT user_id FROM users_editing_page WHERE page_id={$page->id}");
		
		if($result->num_rows) {
			// if found entry not older than 2 minutes trow a message
			// we also want to check if it's same user or not
		   
			// get user_id 
		 	list($user_id) = $result->fetch_row();
			
			// get user from saved user_id in table
		    $user = $this->users->get($user_id); 
		
			// check if current user is same user we output ping script
		    if($user === $this->user){
				$event->return .= $script;
			}
			// if it another user we throw an alert and error message
			else{
				$this->error("Attention! This page is currently being edited by user: <b>{$user->name}</b> ({$user->email})"); 
				$event->return .= "<script>alert('Page is currently being edited by user: {$user->name} ({$user->email})')</script>";
			}
		} 
		else{
			// nobody is currently editing this page so insert user and page id, and output js ajax pinging
			$curr_ts = time();
			$result = $this->db->query("INSERT INTO users_editing_page (page_id,user_id,ts) VALUES({$page->id},{$this->user->id},{$curr_ts})");
			$event->return .= $script;	
		}
		
	}
	
	
	static public function getModuleConfigInputfields(array $data) {
		
		$modules = wire('modules');
		$data = array_merge(self::$defaults, $data);
		
		$fields = new InputfieldWrapper();
		
		$field = $modules->get("InputfieldInteger"); 
		$field->attr('name', 'pingInterval'); 
		$field->attr('value', $data['pingInterval']); 
		$field->label = "Ping interval in ms (default 20000)";
		$fields->append($field);
		
		$field = $modules->get("InputfieldInteger"); 
		$field->attr('name', 'removeLockTimeout'); 
		$field->attr('value', $data['removeLockTimeout']); 
		$field->label = "Remove lock timeout in seconds (default 60)";
		$fields->append($field);
		
		return $fields;
	}
	
	
	public function ___install() {

		$process = $this->modules->get("ProcessPageEditSoftLock");
		$p = new Page();
		$p->template = $this->templates->get("admin");
		$p->parent = $this->pages->get(10);
		$p->title = 'CheckPageEditStatus';
		$p->name = 'checkpagelock';
		$p->process = $process;
		$p->status = Page::statusHidden;
		$p->save();

		$sql = <<< _END

		CREATE TABLE users_editing_page (
		    page_id int unsigned not null,
		    user_id int unsigned not null,
		    ts int unsigned not null,
		    PRIMARY KEY(page_id),
		    KEY(user_id),
		    KEY(ts)
		);

_END;

		$this->db->query($sql);
	}

	public function ___uninstall() {
		try{
			$p = $this->pages->get('template=admin, name=checkpagelock');
			$p->delete();
		} catch( Exception $e ){
			//throw new WireException("Process Admin Page 'checkpagelock' could not be found.");
		}
	
		$this->db->query("DROP TABLE IF EXISTS users_editing_page");
		$this->modules->uninstall("ProcessPageEditSoftLock");
	}
}
?>