<?php

/**
 * ProcessWire, Process Page Edit Soft Lock  Module 1.0.0
 *
 * This module provides function to update edit lock status
 * It will get called through from PageEditSoftLock's js script when editing a page
 *
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2011 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 *
 * @author Philipp 'Soma' Urlich, philipp at urlich dot ch
 *
 * @date 27/10/2011
 * 
 *
 */

class ProcessPageEditSoftLock extends Process{
	
	
	public static function getModuleInfo() {
		return array(
			'title' => 'Process Page Edit Soft Lock',
			'summary' => 'Provides admin process page for the "Page Edit Soft Lock" module.',
			'version' => 100,
			'href' => 'http://processwire.com/talk/index.php/topic,637.0.html',
			'permanent' => false,
			'singular' => true, 
			'autoload' => true,
			'permission' => 'page-edit'
		);
	}
	

	public function ___execute(){
		
	}
	
	public function executeUpdateStatus(){
		
		$time = time(); 

		$user_id = (int) $this->input->get->user_id;
		$page_id = (int) $this->input->get->page_id;
		
		if(!$user_id || !$page_id) return;
		
		try {
		   $this->db->query("INSERT INTO users_editing_page SET page_id=$page_id, user_id=$user_id, ts=$time"); 
		} catch(Exception $e) {
		   // already here
		   $this->db->query("UPDATE users_editing_page SET ts=$time WHERE user_id=$user_id AND page_id=$page_id"); 
		}
		
		$this->message("Well hello $user_id");
		return "user_id: ".$user_id;
	}
	


}
